baseURL: "http://www.bittenbypython.com/"
languageCode: "fr-FR"
title: "Bitten By Python"
pagination.pagerSize: 10
theme: "PaperMod"

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languages:
  fr:
    contentDir: content/fr
    disabled: false
    languageCode: fr-FR
    languageDirection: ltr
    languageName: Français
    title: Bitten By Python
    weight: 1
  en:
    contentDir: content/en
    disabled: true
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Reference, Tutorials, and Explanations
    title: Project Documentation
    weight: 2

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
    env: production
    title: "Bitten By Python"
    description: "Je partage mes connaissances avec vous"
    keywords: [Python, IA, Go, Golang]
    author: Gwenaël Nardin
    DateFormat: "2 Jan 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: true
    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    disableSpecial1stPost: true
    showtoc: false

    homeInfoParams:
        Title: "Bitten By Python \U0001F44B"
        Content: "Python, Go et autre"
    
    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/gwenael-nardin/"
        - name: github
          url: "https://github.com/yeswearecoding"
